model:
  # Specify lr_init and cd_rate with `ray.tune.choice` so they show up on CLIReporter
  lr_init:
    _target_: ray.tune.choice
    categories:
      - 1.0e-2
  cd_rate:
    _target_: ray.tune.choice
    categories:
      - 0.5
  dropout_rate:
    _target_: ray.tune.uniform
    lower: 0.0
    upper: 0.6
  l2_gen_scale:
    _target_: ray.tune.loguniform
    lower: 1.0e-4
    upper: 1.0e-0
  l2_con_scale:
    _target_: ray.tune.loguniform
    lower: 1.0e-4
    upper: 1.0e-0
  kl_co_scale:
    _target_: ray.tune.loguniform
    lower: 1.0e-6
    upper: 1.0e-4
  kl_ic_scale:
    _target_: ray.tune.loguniform
    lower: 1.0e-5
    upper: 1.0e-3
