csv_logger:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${oc.env:PWD}
  name: ""

tensorboard_logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${oc.env:PWD}
  name: ""
