defaults:
  # Set these defaults inside `ray_tune_run_kwargs`
  - scheduler@ray_tune_run_kwargs.scheduler: fifo
  - search_space@ray_tune_run_kwargs.config: autolfads_chaotic
  # Use colored logger
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

run_tag: ???
runs_home: /snel/share/runs/lfads-torch/testing
config_train: multi_train.yaml
local_mode: False
overwrite: True

ray_tune_run_kwargs:
  name: ${run_tag}
  metric: valid/recon_smth
  mode: min
  resources_per_trial:
    cpu: 3
    gpu: 0.5
  search_alg:
    _target_: ray.tune.suggest.basic_variant.BasicVariantGenerator
    random_state: 0
  trial_dirname_creator:
    _target_: lfads_torch.utils.ray_tune.get_trial_dirname_creator
  num_samples: 20
  progress_reporter:
    _target_: ray.tune.CLIReporter
    metric_columns:
      - valid/recon_smth
      - cur_epoch
    sort_by_metric: True
  # With `name`, a hack to get `ray.tune` to use the directory created by `hydra`.
  local_dir: ".."
  verbose: 1

hydra:
  run:
    dir: ${runs_home}/multi/${run_tag}
  output_subdir: null
