defaults:
  - scheduler: pbt
  # Use colored logger
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

run_tag: ???
runs_home: /snel/share/runs/lfads-torch/testing
config_train: pbt_train.yaml

ray_tune_run:
  name: ${run_tag}
  metric: valid/recon
  mode: min
  resources_per_trial:
    cpu: 3
    gpu: 0.5
  # TODO: Debug for deterministic samples
  # search_alg:
  #   _target_: ray.tune.suggest.basic_variant.BasicVariantGenerator
  #   random_state: 0
  num_samples: 40
  reuse_actors: True
  keep_checkpoints_num: 1
  # With `name`, a hack to get `ray.tune` to use the directory created by `hydra`.
  local_dir: ".."
  verbose: 1

search_space:
  model:
    lr_init: 1.0e-2
    cd_rate: 0.5
    dropout_rate:
      _target_: ray.tune.uniform
      lower: 0.0
      upper: 0.6
    l2_gen_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-4
      upper: 1.0e-0
    l2_con_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-4
      upper: 1.0e-0
    kl_co_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-6
      upper: 1.0e-4
    kl_ic_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-5
      upper: 1.0e-3

progress_reporter:
  _target_: ray.tune.CLIReporter
  metric_columns:
    - valid/recon
    - cur_epoch
  sort_by_metric: True

hydra:
  run:
    dir: ${runs_home}/pbt/${run_tag}
  output_subdir: null
