model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: valid/recon
  mode: min
  save_top_k: 1
  save_last: True
  verbose: False
  dirpath: "."
  auto_insert_metric_name: True

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: valid/recon
  mode: min
  patience: 200
  min_delta: 0

learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch
