learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch

raster_plot:
  _target_: lfads_torch.callbacks.RasterPlot
  n_samples: 3
  log_every_n_epochs: 20

trajectory_plot_callback:
  _target_: nlb_lightning.callbacks.TrajectoryPlotCallback
  batch_fwd:
    _target_: lfads_torch.utils.misc.get_batch_fwd
  log_every_n_epochs: 5

evaluation_callback:
  _target_: nlb_lightning.callbacks.EvaluationCallback
  batch_fwd:
    _target_: lfads_torch.utils.misc.get_batch_fwd
  log_every_n_epochs: 5
