learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch

valid_raster_plot:
  _target_: lfads_torch.callbacks.RasterPlot
  n_samples: 3
  log_every_n_epochs: 20

train_raster_plot:
  _target_: lfads_torch.callbacks.RasterPlot
  split: train
  n_samples: 3
  log_every_n_epochs: 20

trajectory_plot:
  _target_: lfads_torch.callbacks.TrajectoryPlot
  log_every_n_epochs: 5

evaluation_callback:
  _target_: lfads_torch.callbacks.NLBEvaluation
  log_every_n_epochs: 5
