# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml
  - model: default.yaml
  - datamodule: default.yaml
  - callbacks: default.yaml
  - logger: default.yaml
  # - mode: default.yaml
  # - experiment: null
  # - hparams_search: null
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

runs_home: /snel/share/runs/lfads-torch
# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# check performance on test set, using the best model achieved during training
# lightning chooses best model based on metric specified in checkpoint callback
test_after_training: True

# seed for random number generators in pytorch, numpy and python.random
seed: null

# name of the run, accessed by loggers
name: null

# We may want to replace ${oc.env:USER} with e.g. ${project_name}
hydra:
  run:
    dir: ${runs_home}/single/${oc.env:USER}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${runs_home}/multi/${oc.env:USER}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
