defaults:
  - model: autolfads_chaotic
  - datamodule: autolfads_chaotic
  - callbacks: default
  - logger: default
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - _self_

seed: 0

trainer:
  _target_: pytorch_lightning.Trainer
  gradient_clip_val: 200
  max_epochs: 10_000
  log_every_n_steps: 5
  # Prevent console output by individual models
  enable_progress_bar: False
  enable_model_summary: False

callbacks:
  tune_report_callback:
    _target_: ray.tune.integration.pytorch_lightning.TuneReportCallback
    metrics:
      - train/recon
      - valid/recon
      - cur_epoch
    "on": validation_end

logger:
  tensorboard_logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    # Configure logger so PTL and ray use the same TB file.
    save_dir:
      _target_: ray.tune.get_trial_dir
    version: "."
    name: ""
