_target_: lfads_torch.datamodules.hdf5.HDF5DataModule
data_path: /snel/share/runs/PBT/paper-fix/lfadslite-testing/data_chaotic/chaotic_chaotic_rnn_inputs_2_dataset_N50_S50_1000trials
batch_size: 128
num_workers: 4
ext_input: False
ground_truth: True
# Name these params with `dm_` to avoid overlap w/ model HPS (per `pytorch_lightning==1.4.9`)
dm_sv_rate: ${model.sv_rate}
dm_sv_seed: ${model.sv_seed}
dm_ic_enc_seq_len: ${model.ic_enc_seq_len}
