_target_: lfads_torch.datamodules.base.BasicDataModule
data_paths:
  - /snel/share/share/derived/NW_Emory_Data_Sharing/Jango/2015/stitched/binsize_20ms/run_010/lfads_input/lfads_Jango_20150730_001.h5
  - /snel/share/share/derived/NW_Emory_Data_Sharing/Jango/2015/stitched/binsize_20ms/run_010/lfads_input/lfads_Jango_20150731_001.h5
  - /snel/share/share/derived/NW_Emory_Data_Sharing/Jango/2015/stitched/binsize_20ms/run_010/lfads_input/lfads_Jango_20150827_001.h5
  - /snel/share/share/derived/NW_Emory_Data_Sharing/Jango/2015/stitched/binsize_20ms/run_010/lfads_input/lfads_Jango_20151029_001.h5
  - /snel/share/share/derived/NW_Emory_Data_Sharing/Jango/2015/stitched/binsize_20ms/run_010/lfads_input/lfads_Jango_20151102_001.h5
batch_size: 256
num_workers: 0
sv_rate: 0.0
sv_seed: 0
# Name with `dm_` to avoid overlap w/ model HPS (per `pytorch_lightning==1.4.9`)
dm_ic_enc_seq_len: ${model.ic_enc_seq_len}
