_target_: lfads_torch.datamodules.BasicDataModule
attr_keys:
  - train_decode_mask
  - valid_decode_mask
  - psth
  - train_cond_idx
  - valid_cond_idx


batch_keys:
- behavior
batch_size: 256
datafile_pattern: ${relpath:myData/myTry_000128_5_addMask.h5} # my_lfads_input.h5
