_target_: lfads_torch.datamodules.BasicDataModule
data_paths:
  - ${relpath:datasets/mc_maze_large-05ms-val.h5}
  - ${relpath:datasets/mc_maze_medium-05ms-val.h5}
  - ${relpath:datasets/mc_maze_small-05ms-val.h5}
batch_size: 192
